name: Build & Release Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Get latest tag
      id: get_tag
      run: |
        git fetch --tags
        latest_tag=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
        echo "Latest tag: $latest_tag"
        if [ -z "$latest_tag" ]; then
          echo "version=0.0.1" >> $GITHUB_OUTPUT
        else
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          patch=$((patch + 1))
          echo "version=${major}.${minor}.${patch}" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_tag.outputs.version }}
        name: Release v${{ steps.get_tag.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          smssexe/manpages.ir:latest
          smssexe/manpages.ir:v${{ steps.get_tag.outputs.version }}
