name: Sync README to Docker Hub

on:
  push:
    paths:
      - README.md

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Update README on Docker Hub
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: smssexe/manpages.ir
        readme-filepath: README.md
